### PR TITLE
Feature #52

### PR DESCRIPTION
**Pull request by SaimonasFOS**

### CODE REVIEW

**Comment by Piiit** [comment]
@SaimonasFOS There are conflicts, please resolve them... I may have merged in the wrong order here, sorry about that

**Comment by SaimonasFOS** [comment]
@Piiit Fixed, hope there are no further issues

**Comment by Piiit** [comment]
@SaimonasFOS Thx

**Comment by Piiit** [comment]
Unfortunately, the compilation failed... please see https://github.com/noi-techpark/it.bz.opendatahub.epaper.api/runs/5004193310?check_suite_focus=true for details

**Comment by Piiit** [comment]
@SaimonasFOS FYI

**Pull request merged**
